### ISSUE TITLE
node server.js start errors

### ISSUE THREAD

**Issue by ghost** [jquery-ui-bootstrap/jquery-ui-bootstrap#265]
i have cloned the new version jquery-ui-bootstrap and run node js
➜  jquery-ui-bootstrap git:(masterbs3) node server.js

/Users/qk/github/jquery-ui-bootstrap/server.js:10
app.configure( function() {
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (/Users/qk/github/jquery-ui-bootstrap/server.js:10:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
➜  jquery-ui-bootstrap git:(masterbs3)

**Comment by nicdutil** [comment]
A quick fix: 
In package.json, change: 
"express": ^4.12.2 
to
"express": ^3.21.0

Some work will need to be done to get this file working in express 4 (i.e remove configure and
replace express middleware by third party ones).
